Dockerize (wip)

diff --git a/gbif-taxonomy-for-la b/gbif-taxonomy-for-la
--- a/gbif-taxonomy-for-la
+++ b/gbif-taxonomy-for-la
@@ -2,8 +2,8 @@
 
 set -e
 
-T=./target
-B=$T/backbone
+T=/data/lucene/target
+B=/data/lucene/target/backbone
 DATE=$(date +%Y-%m-%d_%H-%M)
 
 CMD=$(basename "$0")
@@ -28,6 +28,8 @@ Usage: $CMD [options] <release-date>
 Options:
       --backbone                    Download GBIF backbone taxonomy
       --name-authors                Split name and authors from the GBIF backbone
+      --prepare-tests               Prepare tests
+      --tests                       Run tests
       --namematching-distri=<nmv>   Download ALA namematching-distribution version [default: 4.2].
       --namematching-index          Generate namematching index
       --namematching-index-legacy   Generate namematching index legacy (pre namemaching-service)
@@ -45,37 +47,54 @@ EOF
 
 if [[ ! -d "$T" ]]
 then
-  mkdir "$T"
+  mkdir -p "$T"
 fi
 
 if ($backbone)
 then
   wget -O $T/backbone.zip https://hosted-datasets.gbif.org/datasets/backbone/current/backbone.zip
-  if [[ -d "$B" ]]
+  if [[ -d "$T/backbone" ]]
   then
     mv "$T/backbone" "$T/backbone-pre-$DATE"
   fi
-  (cd $T; mkdir backbone; cd backbone; unzip -q ../backbone.zip)
+  (cd $T; mkdir backbone; cd backbone; unzip -q $T/backbone.zip)
   rm "$T/backbone.zip"
-fi
 
-if ($name_authors)
-then
   if [[ ! -f "$B/Taxon.tsv.orig" ]]; then
     echo "Taxon.tsv.orig doesn't exist. Creating it"
     mv "$B/Taxon.tsv" "$B/Taxon.tsv.orig"
   fi
+fi
 
-  if [[ ! -f "$B/Taxon-tests.tsv" ]]
-  then
-    head -100000 "$B/Taxon.tsv.orig" > "$B/Taxon-tests.tsv"
-  fi
+if ($prepare_tests)
+then
+  echo "Creating a test file with the first 10000 lines and names included in tests"
+  head -10000 "$B/Taxon.tsv.orig" > "$B/Taxon-tests.tsv"
+  grep -oP 'grepName\("\K[^"]*' test/taxonTransformTests.js | while read -r line
+  do
+    output=$(grep -m 1 "$line" "$B/Taxon.tsv.orig" || true)
+    if [ -z "$output" ]; then
+      echo "The specie '$line' was not found, so the test will fail"
+    else
+      echo "$output" >> "$B/Taxon-tests.tsv"
+    fi
+  done
+  echo "Spliting scientificName and scientificNameAuthorship"
+  node main.js "$B/Taxon-tests.tsv" "$B/issues.tsv" > "$B/Taxon.tsv"
+fi
 
+if ($name_authors)
+then
   echo "Trying to install node deps"
   npm install
 
   echo "Spliting scientificName and scientificNameAuthorship"
-  node main.js > "$B/Taxon.tsv"
+  node main.js "$B/Taxon.tsv.orig" "$B/issues.tsv" > "$B/Taxon.tsv"
+fi
+
+if ($tests)
+then
+  env TAXON_FILE="$B/Taxon-tests.tsv" mocha
 fi
 
 # https://github.com/AtlasOfLivingAustralia/ala-name-matching
@@ -90,10 +109,10 @@ echo Fixing: https://github.com/gbif/portal-feedback/issues/3781
 egrep -v '^2925549	\\.*The Woody Plants of Korea' "$B/VernacularName.tsv" > "$B/VernacularName.tsv.fixed"
 mv "$B/VernacularName.tsv.fixed" "$B/VernacularName.tsv"
 
-echo Trying to patch col_vernacular.txt
-cp col_vernacular.txt.patch /data/lucene/sources
-OUT="$(cd /data/lucene/sources; patch -p0 -r - --forward < col_vernacular.txt.patch)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false);
-echo $OUT
+# echo Trying to patch col_vernacular.txt
+# cp col_vernacular.txt.patch /data/lucene/sources
+# OUT="$(cd /data/lucene/sources; patch -p0 -r - --forward < col_vernacular.txt.patch)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false);
+# echo $OUT
 
 if ($namematching_index_legacy)
 then
@@ -108,8 +127,10 @@ then
     rm "$T/$NTL"
   fi
 
-  java -Dlog4j.configuration=file:/usr/lib/nameindexer/log4j.xml -Dfile.encoding=UTF8 -Djava.util.Arrays.useLegacyMergeSort=true -Xmx8g -Xms1g \
-    -jar /usr/lib/nameindexer/nameindexer.*jar -all --dwca $B --irmng /data/lucene/sources/IRMNG_DWC_HOMONYMS --common /data/lucene/sources/col_vernacular.txt
+#  java -Dlog4j.configuration=file:/usr/lib/nameindexer/log4j.xml -Dfile.encoding=UTF8 -Djava.util.Arrays.useLegacyMergeSort=true -Xmx8g -Xms1g \
+#    -jar /usr/lib/nameindexer/nameindexer.*jar -all --dwca $B --irmng /data/lucene/sources/IRMNG_DWC_HOMONYMS
+
+  /usr/lib/nameindexer/index.sh --all --dwca /data/lucene/sources/backbone --target /data/lucene/namematching --irmng /data/lucene/sources/IRMNG_DWC_HOMONYMS/ \
 
   cp -a /data/lucene/namematching "$T/$NTLO"
   (cd "$T"; tar cvfz "$NTL" "$NTLO")
@@ -153,3 +174,4 @@ then
 
   (cd $B; zip "../$DWCA_FILE" * --exclude Taxon.tsv.orig Taxon-tests.tsv issues.tsv *-sorted )
 fi
+
